### ISSUE TITLE
Everything is fine

### ISSUE THREAD

**Issue by hhoffstaette** [mulle-nat/LD_PRELOAD-breakage-linux#1]
Both the documentation and resulting behaviour are correct and everything works exactly as it should. Really :)

- *load* order can be examined by export-ing your LD_PRELOAD line and inspecting the result with ldd. This will initialize your preload lib and run its constructors (for the ldd executable), but it will also show the correctly interposed load order for the main executable.

- a common misconception is that load order is execution order. *This is not the case*, and it's a frequent source of bugs when people tryto  get smart with C++ constructor initialization in shared libraries, which is essentially useless in larger systems. Your use of ```__attribute__((constructor))``` is exactly that.

- [This posting](https://stackoverflow.com/questions/11106875/attribute-constructor-call-order-confusion) should explains things.

I regularly use nocache, eatmydata and faketime on Linux to interpose things and they all work fine.

**Comment by mulle-nat** [comment]
I looked at the posting, but this seems to be only concerned about initialization order on the `.o` scope. But we are in `.so` scope here. So I didn't get much out of that.

Looking at `ldd` is indeed a good idea, as it shows that  `libld-preload.so` appears first:

```
nat@terodde:/home/src/srcO/mulle-core/mulle-testallocator/research/ld-preload$ LD_PRELOAD="${PWD}/build/libld-preload.so" ldd ./build/main
load_preload
	linux-vdso.so.1 (0x00007ffe38370000)
	/home/src/srcO/mulle-core/mulle-testallocator/research/ld-preload/build/libld-preload.so (0x00007f078ff24000)
	liblinked.so => /home/src/srcO/mulle-core/mulle-testallocator/research/ld-preload/build/liblinked.so (0x00007f078ff1f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f078fcea000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f078ff30000)
```

If you have a shared library, it is guaranteed that it's dependencies are loaded first before the constructor is run (pretty basic, if you are linking against glibc and you need `printf` f.e.).

Executing  `liblinked.so` constructor ahead of `libld-preload.so` makes no sense to me here.

**Comment by mulle-nat** [comment]
Leichte Langeweile bei Corona und Zeit mal alte issues aufzuräumen ?  😄
